### ISSUE TITLE
Обсервер

### ISSUE THREAD

**Issue by Azmodan95** [Ramil192/jquerySlider#16]
Сейчас для каждого типа данных передаваемых через обсервер создается интерфейс описывающий класс обсервера, по этой причине я подозреваю что обсервер и не реализует ни один из интерфейсов. Из этого появляется еще одна проблема у обсервера появляется информация о типах передаваемых данных. У тебя же обсервер имеет тип дженерик, так почему бы этот тип не использовать? Можно сделать интерфейс тоже типа дженерик 
```
export interface IObserver<T> {
  observers: Array<(obj: T) => void>;

  addObserver(observer: (obj: T) => void): void;
  callAllObserver(obj: T): void;
}
```
И в момент использования уже передавать нужный тип данных:
```
IObserver<IObserverLeftArgument>
```
И тогда сам класс сможет реализовать этот интерфейс
```
class Observer<T> implements IObserver<T>
```
Так же есть некоторая проблема в самом использовании обсервера, сейчас контроллер создает экземпляры обсервера и их прокидывает в модель и вид, зачем так сделано? В контроллере оказывается в этом случае информация обо всех подписчиках, контроллер должен реагировать на обновления вида/модели и уже обновлять вид/модель, а сейчас он по сути только подписывает модель на события вида, и наоборот вид на события модели. И тут появляется проблема технически в один экземпляр обсервера можем добавить и вид и модель. Чтобы этого избежать можно вынести логику обсервера в модель и вид, и контроллер будет уже подписываться на события модели или вида и обновлять модель или вид.

**Comment by Azmodan95** [comment]
Я имел в виду вообще убрать создание экземпляра обсервера в контроллере. Чтобы у вида и модели бы свой собственный экземляр, и только они бы знали о своих подписчиках, а контроллер бы подписывался бы на эти события и уже реагировал соответствующим образом, и достаточно по одному экземпляру обсервера для модели и вида. И еще если тебе нужно получить функционал одного класса внутри другого не нужно это делать через свойство, нужно применять наследование. Приведу пример как это можно реализовать на примере модели:
В модели ты только вызываешь метод оповещение подписчиков при обновлении чего-то, и передаешь нужные данные с типом события которое произошло, это нужно для того чтобы подписчики поняли что конкретно за событие произошло, можно конечно пойти еще дальше и реализовать что-то наподобие addEventListener. Но для этого нужна более сложная логика в обсервера вполне достаточно того что есть сейчас.
```
class Model extends Observer {
    valueUpdate() {
       this.callAllObserver({ type: 'value-update', value: {} });
    }
}
```
Затем в контроллере ты добавляешь подписчика и функцию которая будет вызываться при наступлении события:
```
class Controller {
    observeModelChange() {
      this.model.addObserver((data) => {
         switch(data.type) {
           case 'value-update':
             this.view.update(data.value);
         }
      })
    }
}
```
С видом будет все аналогичным образом.
Так же интерфейсы, которые описывают типы данных передаваемые через обсервер нужно вынести в интерфейсы модели или вида, в зависимости от того где они генерируются.
Еще момент, сейчас в именах имени методов обсервера дублируется имя класса, это не очень хорошо, лучше заменить на что-то другое к примеру "Subscriber" или возможно как-то по другому их назвать.

**Comment by Azmodan95** [comment]
https://github.com/Ramil192/jquerySlider/blob/d89aa9b99fd0d7241e2103fdcef8a18f49e3422c/src/mvc/Controller/Controller.ts#L41
Если не используется default в switch case и чтобы убрать предупреждение eslint, достаточно написать комментарий "no default"
```
switch (data.type) {
  case ModelActionTypes.RENDER:
    this.view.render(data.value); break;
  // no default
}
```

**Comment by Ramil192** [comment]
![image](https://user-images.githubusercontent.com/61628421/134663490-c188e5b3-44d2-4db0-8ec0-50d8800d8102.png)
Добавил
