### ISSUE TITLE
Функционал слайдера

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/jquerySlider#2]
1. Не понятно зачем часть инпутов vertical disabled, лучше если со всеми можно будет взаимодействовать 
![2021-07-19_09-54](https://user-images.githubusercontent.com/85491485/126116599-97bc92e7-be78-4ad1-a090-7f1130a28d5c.png)

2.Лейбл тоже должен быть интерактивный и им можно передвигать ползунок. Сейчас это просто текст
![2021-07-19_10-00](https://user-images.githubusercontent.com/85491485/126116822-cce2b7ff-2496-4a2d-9dbc-3c4650bdf079.png)

3. При вертикальном положении слайдер выходит из области настроек, а часть все еще остается в нем. Смотрится, как будир верстка сломана.
![2021-07-19_10-06](https://user-images.githubusercontent.com/85491485/126117376-14878381-b48a-424e-bda4-209c07cbf1ea.png)

4.Не могу ввести в поле step дробные значения(0.2), они должны поддерживаться

5. При клике по треку ползунок также должен перемещаться на это место, сейчас ничего не происходит

**Comment by Ramil192** [comment]
![image](https://user-images.githubusercontent.com/61628421/126161818-1ad8ac87-cd2d-4707-a512-19c04e0d245c.png)
2 В тз нету такого требование,

**Comment by DmitrijMTP** [comment]
> ![image](https://user-images.githubusercontent.com/61628421/126161818-1ad8ac87-cd2d-4707-a512-19c04e0d245c.png)
> Пункт 2 В тз нету такого требование,

Прямо не прописано, но он должен быть интерактивным
По клике по треку ничего не происходит также

**Comment by DmitrijMTP** [comment]
1.Tooltip теперь работает. Но остался с ним один момент: правый работает отлично, но левый  "отпрыгивает в сторону" при смещении его. То есть он должен при смещении находится примерно по середине указателя мыши

https://user-images.githubusercontent.com/85491485/126750326-72de26f7-c0f1-4981-b555-b17e8dfa2874.mp4

2.Пр клике по треку не смещается ползунок.Если не понятно, как это должно работать прикрепил внизу видео с демонстрацией

https://user-images.githubusercontent.com/85491485/126751181-4a59c82d-3295-4486-92ee-a612acbcadae.mp4

**Comment by Ramil192** [comment]
2 сделал работает только тогда когда один слайдер

**Comment by DmitrijMTP** [comment]
Остался один момент: как при клике, так и при перемещении ползунок перемещается в свою начальную часть, а нужно чтобы он оказался в середине. Скорее всего это из-за того, что ты не учитываешь размер элемента при расчете координат. То есть к координатам нужно добавлять половину размера "кругляшка" или тултипа. Из-за этого создается эффект "отпрыгивания" при перемещении.

https://user-images.githubusercontent.com/85491485/126952079-16683e9f-ad25-47ad-941c-a1f2de1b2d62.mp4

**Comment by DmitrijMTP** [comment]
C перемещение теперь хорошо.
Другие проблемы:
1.Ползунок max выходит за пределы трека
![2021-07-27_16-46](https://user-images.githubusercontent.com/85491485/127165045-b06ef6bd-9224-4469-80f6-5477599bb87f.png)
2.Сломался клик по треку

https://user-images.githubusercontent.com/85491485/127165450-b6dba41d-f1b1-40a9-ab5b-148b66eed098.mp4
