### ISSUE TITLE
Архитектура

### ISSUE THREAD

**Issue by Azmodan95** [Ramil192/jquerySlider#20]
Сейчас значения ширины передается в модель, модель ничего не должна знать о виде, и в целом ни какой привязки к реализации вида быть не должно, так как могут быть различные реализации видов. В модели должны быть данные только связанные с бизнес логикой, не должно быть ни каких вычислений связанных с видом.

**Comment by Ramil192** [comment]
тут width , но это обработка клика по track
![image](https://user-images.githubusercontent.com/61628421/135305088-c6ea590e-3d4f-4424-84c7-b47cdf15c71e.png)

**Comment by Azmodan95** [comment]
> тут width , но это обработка клика по track ![image](https://user-images.githubusercontent.com/61628421/135305088-c6ea590e-3d4f-4424-84c7-b47cdf15c71e.png)

Хорошо, но зачем модели знать о координатах и ширине? В модели не должно быть вычислений связанных с видом. Расчеты с шириной и координатами должны быть в виде, то есть в данном случае вид должен вычислить процент и передает его модели, а модель уже будет вычислять новое значение на основе него.
