### ISSUE TITLE
Ошибки работы слайдера

### ISSUE THREAD

**Issue by DmitrijMTP** [Ramil192/jquerySlider#3]
1. При клике по шкале не перемещается ползунок между двух значений
https://user-images.githubusercontent.com/85491485/126118548-831dac6e-404b-42bc-a4fc-4026acba734f.mp4

2.Если установить значение меньше максимума, слайдер перестает работать 
https://user-images.githubusercontent.com/85491485/126119929-399b3e4d-ab90-43a6-9cf2-7c33237976ce.mp4

3.В вертикальном положении он работает как-то "наоборот" ,обычно если от 0 до 100, 0 наверху, внизу 100
![2021-07-19_10-31](https://user-images.githubusercontent.com/85491485/126120690-23a86d4a-fc90-46b7-865f-ca155af57d89.png)

4.При от 0 до 100 и шаге 7, минимальное значение 98, а не 100
![2021-07-19_10-35](https://user-images.githubusercontent.com/85491485/126120951-86cdc595-71c3-464f-a633-2f5a09d17c9e.png)

**Comment by Ramil192** [comment]
3 пункт 
            1 в тз нет такого пункта , 
            2 это не логично так как 5 ти этажный дом начинается с 1 ого этажа
 
https://user-images.githubusercontent.com/61628421/126181841-892cd655-82cd-4a9b-8955-a54004cc8c8f.mp4
4 так как 98+7 = 105 а не 100 если поставит при этом макс 105 все работает

**Comment by DmitrijMTP** [comment]
1. По этому пункту в issue #2 есть тоже самое, отсюда уберем, чтобы не дублировать
2. также ломается 

https://user-images.githubusercontent.com/85491485/126344444-db65b0c1-1df3-4d66-8c21-4c834d9a0732.mp4

3. ок

**Comment by DmitrijMTP** [comment]
1.Теперь ползунок перемещается на значение превышающие максимум
![2021-07-23_10-47](https://user-images.githubusercontent.com/85491485/126752159-08b77365-1871-43a9-ae20-f67e27e5132d.png)

2.Еще баг

https://user-images.githubusercontent.com/85491485/126752987-65df4932-e349-49ce-8446-587da9674bf7.mp4

**Comment by Ramil192** [comment]
2 у меня правый ползунок не может проталкивать левый.

**Comment by DmitrijMTP** [comment]
Теперь не выходит за максимум, но на максимальном значении при шаге 7, например, у тултипа значение 97, а должно быть 100. Если не понятно, как это сделать - просто добавь проверку когда обновляется значение тултипа и если координаты равны или превышаются размер трека, то возвращай максимальное значение. Это просто один из вариантов реализации, возможна другая логика.
![2021-07-26_10-51](https://user-images.githubusercontent.com/85491485/126953440-1b01a6a4-b424-480d-9dcc-c4d0f1e7741b.png)

Что-то странное происходит, перестает сдвигаться:

https://user-images.githubusercontent.com/85491485/126955280-9b500229-7f9d-47b7-b3d3-09200c767829.mp4

**Comment by DmitrijMTP** [comment]
Если перетащить ползунки на максимум, то левый не сдвигается


https://user-images.githubusercontent.com/85491485/127170147-8d5f276c-c945-4363-8a0b-8caaaa219434.mp4

У обоих ползунков устанавливаются одинаковые координаты, скорее всего из-за этого ломается
![2021-07-27_17-18](https://user-images.githubusercontent.com/85491485/127170434-8b88cc38-3e69-45ce-8a72-2d85ad35961a.png)

**Comment by DmitrijMTP** [comment]
Остался последний недочет:

https://user-images.githubusercontent.com/85491485/127621824-9a2bcace-a9f7-4107-b72a-174a3e5c73bd.mp4

При клике левый ползунок перемещается правильно. Осталось сделать также для правого, сейчас он перемещается не в середину "кругляша", а на один из его краев

**Comment by DmitrijMTP** [comment]
В целом хорошо, только при больших значениях тоолтип "съезжает", отцентрируй по середине плиз
![2021-08-03_20-18](https://user-images.githubusercontent.com/85491485/128058557-cc058a77-8b2d-4e82-a5bb-8cc0b426377d.png)
И добавь курсор поинтер на интерактивные элементы
